# Generated by Django 4.1.7 on 2023-04-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toemail', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('messages', models.TextField(verbose_name='500')),
                ('file', models.FileField(max_length=300, upload_to='files')),
            ],
            options={
                'db_table': 'mails',
            },
        ),
    ]
